services:
  bank-api:
    build:
      context: ./BankAccount
      dockerfile: Dockerfile
    ports:
      - "5000:80"               
    depends_on:
      - keycloak
    volumes:
      - /c/Users/Admin/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "18080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: