services:
  bank-api:
    build:
      context: ./BankAccount
      dockerfile: Dockerfile
    ports:
      - "5000:80"     
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production      
      - ConnectionStrings__DefaultConnection=Host=db;Database=mydb;Username=postgres;Password=qwerty123    
    depends_on:
      - db
      - keycloak
    volumes:
      - /c/Users/Admin/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - my-network
    command: >
      sh -c "
        dotnet ef database update --connection \"$ConnectionStrings__DefaultConnection\" &&
        dotnet BankAccount.dll
      "

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "18080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - my-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  keycloak_data:
  pgdata:

networks:
  my-network:
    driver: bridge